//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vvmes.rc
//
#define IDS_VVM_LOAD_ERROR              101
#define IDS_VVM_FAILURE_TO_LOAD_MINUS_1 102
#define IDS_VVM_FAILURE_TO_INITIALIZE_MINUS_2 103
#define IDS_VVM_INITIALIZE_ERROR        104
#define IDS_IDENTIFIER                  105
#define IDS_LANGUAGE                    105
#define IDS_VVM_FAILURE_TO_LOAD_VVMMC_MINUS_3 106
#define IDS_VVM_TEST_OK                 107
#define IDS_VVM_TEST_FAILURE            108
#define IDS_VVM_TEST_HEADING            109
#define IDS_VVM_RUNNING                 110
#define IDS_VVM_TESTING                 111
#define IDS_VVM_TEST_FAILURE_DISPLAY    112
#define IDS_VVM_TEST_OK_DISPLAY         113
#define IDS_VVM_TEST_SHA1_TESTING       114
#define IDS_VVM_TEST_SHA1_PASSED        115
#define IDS_VVM_TEST_SHA1_FIPS_PUB_180_1 116
#define IDS_VVM_TEST_PASS               117
#define IDS_VVM_TEST_FAIL               118
#define IDS_VVM_TEST_BXML_TESTING       119
#define IDS_VVM_TEST_BXML_PASSED        120
#define IDS_VVM_TEST_BXML_1             121
#define IDS_VVM_1DOTDOTDOT              122
#define IDS_VVM_2DOTDOTDOT              123
#define IDS_VVM_3DOTDOTDOT              124
#define IDS_VVM_4DOTDOTDOT              125
#define IDS_VVM_5DOTDOTDOT              126
#define IDS_VVM_6DOTDOTDOT              127
#define IDS_VVM_7DOTDOTDOT              128
#define IDS_VVM_8DOTDOTDOT              129
#define IDS_VVM_9DOTDOTDOT              130
#define IDS_VVM_TEST_BXML_INVALID_FILE  131
#define IDS_VVM_TEST_BXML_UNABLE_TO_LOAD 132
#define IDS_VVM_TEST_BXML_2             133
#define IDS_VVM_TEST_BXML_UNABLE_TO_GET_TEMP_FILE 134
#define IDS_VVM_TEST_BXML_UNABLE_TO_RELOAD_TEMP_FILE 135
#define IDS_VVM_TEST_BXML_RELOAD_DOES_NOT_MATCH 136
#define IDS_VVM_TEST_BXML_3             137
#define IDS_VVM_TEST_BXML_COPY_FAILED   138
#define IDS_VVM_TEST_CANVAS_TESTING     139
#define IDS_VVM_TEST_CANVAS_PASSED      140
#define IDS_VVM_TEST_CANVAS_1           141
#define IDS_VVM_TEST_CANVAS_INVALID_GRADIENT 142
#define IDS_VVM_TEST_CANVAS_SCALED_INVALID_GRADIENT 143
#define IDS_VVM_TEST_CANVAS_CANNOT_CREATE 144
#define IDS_VVM_TEST_CANVAS_SCALED_CANNOT_CREATE 145
#define IDS_VVM_TEST_SLL_TESTING        146
#define IDS_VVM_TEST_SLL_PASSED         147
#define IDS_VVM_TEST_SLL_CREATE         148
#define IDS_VVM_TEST_SLL_APPEND         149
#define IDS_VVM_TEST_SLL_DELETE         150
#define IDS_VVM_TEST_SLL4_TESTING       151
#define IDS_VVM_TEST_SLL4_PASSED        152
#define IDS_VVM_TEST_SLL4_CREATE        153
#define IDS_VVM_TEST_SLL4_APPEND        154
#define IDS_VVM_TEST_SLL4_DELETE        155
#define IDS_VVM_TEST_SLL_UNABLE_TO_CREATE 156
#define IDS_VVM_TEST_SLL4_UNABLE_TO_CREATE 157
#define IDS_VVM_TEST_SLL_SHA1_FAILURE   158
#define IDS_VVM_TEST_SLL4_SHA1_FAILURE  159
#define IDS_VVM_TEST_SLL4_UNABLE_TO_CREATE_CHAIN 160
#define IDS_BXML_NO_ERROR               2000
#define IDS_BXML_UNABLE_TO_CREATE_BXML  2001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
